[package]
name = "gomoku"
version = "0.1.0"
authors = ["jafaghpo <jafaghpo@student.42.fr>"]
edition = "2018"

[dependencies]
clap = { version = "2.33.0", features = ["yaml"] }
sdl2 = { version = "0.32", default-features = false, features = ["image"] }